baseURL = 'https://Lightdust2024.github.io/'
locale = 'zh'
title = 'Lightdust的个人博客'
theme = "stack"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  cdnUrl = "https://cdn.jsdelivr.net/gh/lightdust2024/lightdust2024.github.io@main"